Repository KhronosGroup/SPIRV-LLVM-Translator, pull requests merged in 2020-10, with the labels that each got.

#770 Move clang-format and cland-tidy to GitHub Actions
  .github/workflows/check-code-style.yml
  .travis.yml
  lib/SPIRV/libSPIRV/OpenCL.std.h
  lib/SPIRV/libSPIRV/spirv.hpp
  utils/check_code_format.sh
  utils/check_code_tidyness.sh
  utils/clang-tidy-diff.py
Labels: enhancement

#794 Lower constant expressions inside metadata operands
  lib/SPIRV/SPIRVLowerConstExpr.cpp
  test/lshr-constexpr.ll
Labels: hacktoberfest-accepted

#802 Improve clang-tidy CI check
  .clang-tidy
  .github/workflows/check-code-style.yml
Labels: CI
